import { DefineComponent, SVGAttributes } from 'vue'

export type IconProps = SVGAttributes & {
  size?: string | number
  color?: string
  strokeWidth?: string | number
}

export declare const ZoomOut: DefineComponent<IconProps>
export declare const ZoomIn: DefineComponent<IconProps>
export declare const Zap: DefineComponent<IconProps>
export declare const ZapSquare: DefineComponent<IconProps>
export declare const ZapOff: DefineComponent<IconProps>
export declare const ZapFast: DefineComponent<IconProps>
export declare const ZapCircle: DefineComponent<IconProps>
export declare const Youtube: DefineComponent<IconProps>
export declare const X: DefineComponent<IconProps>
export declare const XSquare: DefineComponent<IconProps>
export declare const XClose: DefineComponent<IconProps>
export declare const XCircle: DefineComponent<IconProps>
export declare const Wind03: DefineComponent<IconProps>
export declare const Wind02: DefineComponent<IconProps>
export declare const Wind01: DefineComponent<IconProps>
export declare const Wifi: DefineComponent<IconProps>
export declare const WifiOff: DefineComponent<IconProps>
export declare const Webcam02: DefineComponent<IconProps>
export declare const Webcam01: DefineComponent<IconProps>
export declare const Waves: DefineComponent<IconProps>
export declare const WatchSquare: DefineComponent<IconProps>
export declare const WatchCircle: DefineComponent<IconProps>
export declare const Wallet05: DefineComponent<IconProps>
export declare const Wallet04: DefineComponent<IconProps>
export declare const Wallet03: DefineComponent<IconProps>
export declare const Wallet02: DefineComponent<IconProps>
export declare const Wallet01: DefineComponent<IconProps>
export declare const VolumeX: DefineComponent<IconProps>
export declare const VolumePlus: DefineComponent<IconProps>
export declare const VolumeMinus: DefineComponent<IconProps>
export declare const VolumeMin: DefineComponent<IconProps>
export declare const VolumeMax: DefineComponent<IconProps>
export declare const Voicemail: DefineComponent<IconProps>
export declare const Virus: DefineComponent<IconProps>
export declare const VideoRecorder: DefineComponent<IconProps>
export declare const VideoRecorderOff: DefineComponent<IconProps>
export declare const Variable: DefineComponent<IconProps>
export declare const UsersX: DefineComponent<IconProps>
export declare const UsersUp: DefineComponent<IconProps>
export declare const UsersRight: DefineComponent<IconProps>
export declare const UsersPlus: DefineComponent<IconProps>
export declare const UsersMinus: DefineComponent<IconProps>
export declare const UsersLeft: DefineComponent<IconProps>
export declare const UsersEdit: DefineComponent<IconProps>
export declare const UsersDown: DefineComponent<IconProps>
export declare const UsersCheck: DefineComponent<IconProps>
export declare const Users03: DefineComponent<IconProps>
export declare const Users02: DefineComponent<IconProps>
export declare const Users01: DefineComponent<IconProps>
export declare const UserX02: DefineComponent<IconProps>
export declare const UserX01: DefineComponent<IconProps>
export declare const UserUp02: DefineComponent<IconProps>
export declare const UserUp01: DefineComponent<IconProps>
export declare const UserSquare: DefineComponent<IconProps>
export declare const UserRight02: DefineComponent<IconProps>
export declare const UserRight01: DefineComponent<IconProps>
export declare const UserPlus02: DefineComponent<IconProps>
export declare const UserPlus01: DefineComponent<IconProps>
export declare const UserMinus02: DefineComponent<IconProps>
export declare const UserMinus01: DefineComponent<IconProps>
export declare const UserLeft02: DefineComponent<IconProps>
export declare const UserLeft01: DefineComponent<IconProps>
export declare const UserEdit: DefineComponent<IconProps>
export declare const UserDown02: DefineComponent<IconProps>
export declare const UserDown01: DefineComponent<IconProps>
export declare const UserCircle: DefineComponent<IconProps>
export declare const UserCheck02: DefineComponent<IconProps>
export declare const UserCheck01: DefineComponent<IconProps>
export declare const User03: DefineComponent<IconProps>
export declare const User02: DefineComponent<IconProps>
export declare const User01: DefineComponent<IconProps>
export declare const UsbFlashDrive: DefineComponent<IconProps>
export declare const UploadCloud02: DefineComponent<IconProps>
export declare const UploadCloud01: DefineComponent<IconProps>
export declare const Upload04: DefineComponent<IconProps>
export declare const Upload03: DefineComponent<IconProps>
export declare const Upload02: DefineComponent<IconProps>
export declare const Upload01: DefineComponent<IconProps>
export declare const UnderlineSquare: DefineComponent<IconProps>
export declare const Underline02: DefineComponent<IconProps>
export declare const Underline01: DefineComponent<IconProps>
export declare const Umbrella03: DefineComponent<IconProps>
export declare const Umbrella02: DefineComponent<IconProps>
export declare const Umbrella01: DefineComponent<IconProps>
export declare const TypeStrikethrough02: DefineComponent<IconProps>
export declare const TypeStrikethrough01: DefineComponent<IconProps>
export declare const TypeSquare: DefineComponent<IconProps>
export declare const Type02: DefineComponent<IconProps>
export declare const Type01: DefineComponent<IconProps>
export declare const Tv03: DefineComponent<IconProps>
export declare const Tv02: DefineComponent<IconProps>
export declare const Tv01: DefineComponent<IconProps>
export declare const Truck02: DefineComponent<IconProps>
export declare const Truck01: DefineComponent<IconProps>
export declare const Trophy02: DefineComponent<IconProps>
export declare const Trophy01: DefineComponent<IconProps>
export declare const Triangle: DefineComponent<IconProps>
export declare const TrendUp02: DefineComponent<IconProps>
export declare const TrendUp01: DefineComponent<IconProps>
export declare const TrendDown02: DefineComponent<IconProps>
export declare const TrendDown01: DefineComponent<IconProps>
export declare const Trash04: DefineComponent<IconProps>
export declare const Trash03: DefineComponent<IconProps>
export declare const Trash02: DefineComponent<IconProps>
export declare const Trash01: DefineComponent<IconProps>
export declare const Translate02: DefineComponent<IconProps>
export declare const Translate01: DefineComponent<IconProps>
export declare const Transform: DefineComponent<IconProps>
export declare const Tram: DefineComponent<IconProps>
export declare const Train: DefineComponent<IconProps>
export declare const Tool02: DefineComponent<IconProps>
export declare const Tool01: DefineComponent<IconProps>
export declare const Toggle03Right: DefineComponent<IconProps>
export declare const Toggle03Left: DefineComponent<IconProps>
export declare const Toggle02Right: DefineComponent<IconProps>
export declare const Toggle02Left: DefineComponent<IconProps>
export declare const Toggle01Right: DefineComponent<IconProps>
export declare const Toggle01Left: DefineComponent<IconProps>
export declare const Ticket02: DefineComponent<IconProps>
export declare const Ticket01: DefineComponent<IconProps>
export declare const ThumbsUp: DefineComponent<IconProps>
export declare const ThumbsDown: DefineComponent<IconProps>
export declare const ThermometerWarm: DefineComponent<IconProps>
export declare const ThermometerCold: DefineComponent<IconProps>
export declare const Thermometer03: DefineComponent<IconProps>
export declare const Thermometer02: DefineComponent<IconProps>
export declare const Thermometer01: DefineComponent<IconProps>
export declare const TextInput: DefineComponent<IconProps>
export declare const Terminal: DefineComponent<IconProps>
export declare const TerminalSquare: DefineComponent<IconProps>
export declare const TerminalCircle: DefineComponent<IconProps>
export declare const TerminalBrowser: DefineComponent<IconProps>
export declare const Telescope: DefineComponent<IconProps>
export declare const Target05: DefineComponent<IconProps>
export declare const Target04: DefineComponent<IconProps>
export declare const Target03: DefineComponent<IconProps>
export declare const Target02: DefineComponent<IconProps>
export declare const Target01: DefineComponent<IconProps>
export declare const Tag03: DefineComponent<IconProps>
export declare const Tag02: DefineComponent<IconProps>
export declare const Tag01: DefineComponent<IconProps>
export declare const Tablet02: DefineComponent<IconProps>
export declare const Tablet01: DefineComponent<IconProps>
export declare const Table: DefineComponent<IconProps>
export declare const SwitchVertical02: DefineComponent<IconProps>
export declare const SwitchVertical01: DefineComponent<IconProps>
export declare const SwitchHorizontal02: DefineComponent<IconProps>
export declare const SwitchHorizontal01: DefineComponent<IconProps>
export declare const Sunset: DefineComponent<IconProps>
export declare const Sunrise: DefineComponent<IconProps>
export declare const Sun: DefineComponent<IconProps>
export declare const SunSetting03: DefineComponent<IconProps>
export declare const SunSetting02: DefineComponent<IconProps>
export declare const SunSetting01: DefineComponent<IconProps>
export declare const Subscript: DefineComponent<IconProps>
export declare const StrikethroughSquare: DefineComponent<IconProps>
export declare const Strikethrough02: DefineComponent<IconProps>
export declare const Strikethrough01: DefineComponent<IconProps>
export declare const Stop: DefineComponent<IconProps>
export declare const StopSquare: DefineComponent<IconProps>
export declare const StopCircle: DefineComponent<IconProps>
export declare const StickerSquare: DefineComponent<IconProps>
export declare const StickerCircle: DefineComponent<IconProps>
export declare const Stars03: DefineComponent<IconProps>
export declare const Stars02: DefineComponent<IconProps>
export declare const Stars01: DefineComponent<IconProps>
export declare const Star07: DefineComponent<IconProps>
export declare const Star06: DefineComponent<IconProps>
export declare const Star05: DefineComponent<IconProps>
export declare const Star04: DefineComponent<IconProps>
export declare const Star03: DefineComponent<IconProps>
export declare const Star02: DefineComponent<IconProps>
export declare const Star01: DefineComponent<IconProps>
export declare const Stand: DefineComponent<IconProps>
export declare const Square: DefineComponent<IconProps>
export declare const Speedometer04: DefineComponent<IconProps>
export declare const Speedometer03: DefineComponent<IconProps>
export declare const Speedometer02: DefineComponent<IconProps>
export declare const Speedometer01: DefineComponent<IconProps>
export declare const Speaker03: DefineComponent<IconProps>
export declare const Speaker02: DefineComponent<IconProps>
export declare const Speaker01: DefineComponent<IconProps>
export declare const SpacingWidth02: DefineComponent<IconProps>
export declare const SpacingWidth01: DefineComponent<IconProps>
export declare const SpacingHeight02: DefineComponent<IconProps>
export declare const SpacingHeight01: DefineComponent<IconProps>
export declare const Snowflake02: DefineComponent<IconProps>
export declare const Snowflake01: DefineComponent<IconProps>
export declare const Sliders04: DefineComponent<IconProps>
export declare const Sliders03: DefineComponent<IconProps>
export declare const Sliders02: DefineComponent<IconProps>
export declare const Sliders01: DefineComponent<IconProps>
export declare const SlashOctagon: DefineComponent<IconProps>
export declare const SlashDivider: DefineComponent<IconProps>
export declare const SlashCircle02: DefineComponent<IconProps>
export declare const SlashCircle01: DefineComponent<IconProps>
export declare const SkipForward: DefineComponent<IconProps>
export declare const SkipBack: DefineComponent<IconProps>
export declare const Skew: DefineComponent<IconProps>
export declare const Simcard: DefineComponent<IconProps>
export declare const Signal03: DefineComponent<IconProps>
export declare const Signal02: DefineComponent<IconProps>
export declare const Signal01: DefineComponent<IconProps>
export declare const Shuffle02: DefineComponent<IconProps>
export declare const Shuffle01: DefineComponent<IconProps>
export declare const ShoppingCart03: DefineComponent<IconProps>
export declare const ShoppingCart02: DefineComponent<IconProps>
export declare const ShoppingCart01: DefineComponent<IconProps>
export declare const ShoppingBag03: DefineComponent<IconProps>
export declare const ShoppingBag02: DefineComponent<IconProps>
export declare const ShoppingBag01: DefineComponent<IconProps>
export declare const ShieldZap: DefineComponent<IconProps>
export declare const ShieldTick: DefineComponent<IconProps>
export declare const ShieldPlus: DefineComponent<IconProps>
export declare const ShieldOff: DefineComponent<IconProps>
export declare const ShieldDollar: DefineComponent<IconProps>
export declare const Shield03: DefineComponent<IconProps>
export declare const Shield02: DefineComponent<IconProps>
export declare const Shield01: DefineComponent<IconProps>
export declare const Share07: DefineComponent<IconProps>
export declare const Share06: DefineComponent<IconProps>
export declare const Share05: DefineComponent<IconProps>
export declare const Share04: DefineComponent<IconProps>
export declare const Share03: DefineComponent<IconProps>
export declare const Share02: DefineComponent<IconProps>
export declare const Share01: DefineComponent<IconProps>
export declare const Settings04: DefineComponent<IconProps>
export declare const Settings03: DefineComponent<IconProps>
export declare const Settings02: DefineComponent<IconProps>
export declare const Settings01: DefineComponent<IconProps>
export declare const Server06: DefineComponent<IconProps>
export declare const Server05: DefineComponent<IconProps>
export declare const Server04: DefineComponent<IconProps>
export declare const Server03: DefineComponent<IconProps>
export declare const Server02: DefineComponent<IconProps>
export declare const Server01: DefineComponent<IconProps>
export declare const Send03: DefineComponent<IconProps>
export declare const Send02: DefineComponent<IconProps>
export declare const Send01: DefineComponent<IconProps>
export declare const SearchSm: DefineComponent<IconProps>
export declare const SearchRefraction: DefineComponent<IconProps>
export declare const SearchMd: DefineComponent<IconProps>
export declare const SearchLg: DefineComponent<IconProps>
export declare const ScissorsCut02: DefineComponent<IconProps>
export declare const ScissorsCut01: DefineComponent<IconProps>
export declare const Scissors02: DefineComponent<IconProps>
export declare const Scissors01: DefineComponent<IconProps>
export declare const Scan: DefineComponent<IconProps>
export declare const Scales02: DefineComponent<IconProps>
export declare const Scales01: DefineComponent<IconProps>
export declare const Scale03: DefineComponent<IconProps>
export declare const Scale02: DefineComponent<IconProps>
export declare const Scale01: DefineComponent<IconProps>
export declare const Save03: DefineComponent<IconProps>
export declare const Save02: DefineComponent<IconProps>
export declare const Save01: DefineComponent<IconProps>
export declare const Sale04: DefineComponent<IconProps>
export declare const Sale03: DefineComponent<IconProps>
export declare const Sale02: DefineComponent<IconProps>
export declare const Sale01: DefineComponent<IconProps>
export declare const Safe: DefineComponent<IconProps>
export declare const Ruler: DefineComponent<IconProps>
export declare const Rss02: DefineComponent<IconProps>
export declare const Rss01: DefineComponent<IconProps>
export declare const Rows03: DefineComponent<IconProps>
export declare const Rows02: DefineComponent<IconProps>
export declare const Rows01: DefineComponent<IconProps>
export declare const Route: DefineComponent<IconProps>
export declare const RollerBrush: DefineComponent<IconProps>
export declare const Rocket02: DefineComponent<IconProps>
export declare const Rocket01: DefineComponent<IconProps>
export declare const RightIndent02: DefineComponent<IconProps>
export declare const RightIndent01: DefineComponent<IconProps>
export declare const ReverseRight: DefineComponent<IconProps>
export declare const ReverseLeft: DefineComponent<IconProps>
export declare const Repeat04: DefineComponent<IconProps>
export declare const Repeat03: DefineComponent<IconProps>
export declare const Repeat02: DefineComponent<IconProps>
export declare const Repeat01: DefineComponent<IconProps>
export declare const RefreshCw05: DefineComponent<IconProps>
export declare const RefreshCw04: DefineComponent<IconProps>
export declare const RefreshCw03: DefineComponent<IconProps>
export declare const RefreshCw02: DefineComponent<IconProps>
export declare const RefreshCw01: DefineComponent<IconProps>
export declare const RefreshCcw05: DefineComponent<IconProps>
export declare const RefreshCcw04: DefineComponent<IconProps>
export declare const RefreshCcw03: DefineComponent<IconProps>
export declare const RefreshCcw02: DefineComponent<IconProps>
export declare const RefreshCcw01: DefineComponent<IconProps>
export declare const Reflect02: DefineComponent<IconProps>
export declare const Reflect01: DefineComponent<IconProps>
export declare const Recording03: DefineComponent<IconProps>
export declare const Recording02: DefineComponent<IconProps>
export declare const Recording01: DefineComponent<IconProps>
export declare const Receipt: DefineComponent<IconProps>
export declare const ReceiptCheck: DefineComponent<IconProps>
export declare const QrCode02: DefineComponent<IconProps>
export declare const QrCode01: DefineComponent<IconProps>
export declare const PuzzlePiece02: DefineComponent<IconProps>
export declare const PuzzlePiece01: DefineComponent<IconProps>
export declare const Printer: DefineComponent<IconProps>
export declare const PresentationChart03: DefineComponent<IconProps>
export declare const PresentationChart02: DefineComponent<IconProps>
export declare const PresentationChart01: DefineComponent<IconProps>
export declare const Power03: DefineComponent<IconProps>
export declare const Power02: DefineComponent<IconProps>
export declare const Power01: DefineComponent<IconProps>
export declare const Podcast: DefineComponent<IconProps>
export declare const Plus: DefineComponent<IconProps>
export declare const PlusSquare: DefineComponent<IconProps>
export declare const PlusCircle: DefineComponent<IconProps>
export declare const Play: DefineComponent<IconProps>
export declare const PlaySquare: DefineComponent<IconProps>
export declare const PlayCircle: DefineComponent<IconProps>
export declare const Plane: DefineComponent<IconProps>
export declare const Placeholder: DefineComponent<IconProps>
export declare const Pin02: DefineComponent<IconProps>
export declare const Pin01: DefineComponent<IconProps>
export declare const PilcrowSquare: DefineComponent<IconProps>
export declare const Pilcrow02: DefineComponent<IconProps>
export declare const Pilcrow01: DefineComponent<IconProps>
export declare const PiggyBank02: DefineComponent<IconProps>
export declare const PiggyBank01: DefineComponent<IconProps>
export declare const PieChart04: DefineComponent<IconProps>
export declare const PieChart03: DefineComponent<IconProps>
export declare const PieChart02: DefineComponent<IconProps>
export declare const PieChart01: DefineComponent<IconProps>
export declare const Phone: DefineComponent<IconProps>
export declare const PhoneX: DefineComponent<IconProps>
export declare const PhonePlus: DefineComponent<IconProps>
export declare const PhonePause: DefineComponent<IconProps>
export declare const PhoneOutgoing02: DefineComponent<IconProps>
export declare const PhoneOutgoing01: DefineComponent<IconProps>
export declare const PhoneIncoming02: DefineComponent<IconProps>
export declare const PhoneIncoming01: DefineComponent<IconProps>
export declare const PhoneHangUp: DefineComponent<IconProps>
export declare const PhoneCall02: DefineComponent<IconProps>
export declare const PhoneCall01: DefineComponent<IconProps>
export declare const Phone02: DefineComponent<IconProps>
export declare const Phone01: DefineComponent<IconProps>
export declare const Perspective02: DefineComponent<IconProps>
export declare const Perspective01: DefineComponent<IconProps>
export declare const Percent03: DefineComponent<IconProps>
export declare const Percent02: DefineComponent<IconProps>
export declare const Percent01: DefineComponent<IconProps>
export declare const Pentagon: DefineComponent<IconProps>
export declare const PencilLine: DefineComponent<IconProps>
export declare const Pencil02: DefineComponent<IconProps>
export declare const Pencil01: DefineComponent<IconProps>
export declare const PenToolPlus: DefineComponent<IconProps>
export declare const PenToolMinus: DefineComponent<IconProps>
export declare const PenTool02: DefineComponent<IconProps>
export declare const PenTool01: DefineComponent<IconProps>
export declare const PauseSquare: DefineComponent<IconProps>
export declare const PauseCircle: DefineComponent<IconProps>
export declare const Passport: DefineComponent<IconProps>
export declare const Passcode: DefineComponent<IconProps>
export declare const PasscodeLock: DefineComponent<IconProps>
export declare const ParagraphWrap: DefineComponent<IconProps>
export declare const ParagraphSpacing: DefineComponent<IconProps>
export declare const Paperclip: DefineComponent<IconProps>
export declare const Palette: DefineComponent<IconProps>
export declare const Paint: DefineComponent<IconProps>
export declare const PaintPour: DefineComponent<IconProps>
export declare const Package: DefineComponent<IconProps>
export declare const PackageX: DefineComponent<IconProps>
export declare const PackageSearch: DefineComponent<IconProps>
export declare const PackagePlus: DefineComponent<IconProps>
export declare const PackageMinus: DefineComponent<IconProps>
export declare const PackageCheck: DefineComponent<IconProps>
export declare const Octagon: DefineComponent<IconProps>
export declare const NotificationText: DefineComponent<IconProps>
export declare const NotificationMessage: DefineComponent<IconProps>
export declare const NotificationBox: DefineComponent<IconProps>
export declare const NavigationPointerOff02: DefineComponent<IconProps>
export declare const NavigationPointerOff01: DefineComponent<IconProps>
export declare const NavigationPointer02: DefineComponent<IconProps>
export declare const NavigationPointer01: DefineComponent<IconProps>
export declare const MusicNotePlus: DefineComponent<IconProps>
export declare const MusicNote02: DefineComponent<IconProps>
export declare const MusicNote01: DefineComponent<IconProps>
export declare const Move: DefineComponent<IconProps>
export declare const Mouse: DefineComponent<IconProps>
export declare const MoonStar: DefineComponent<IconProps>
export declare const MoonEclipse: DefineComponent<IconProps>
export declare const Moon02: DefineComponent<IconProps>
export declare const Moon01: DefineComponent<IconProps>
export declare const Monitor05: DefineComponent<IconProps>
export declare const Monitor04: DefineComponent<IconProps>
export declare const Monitor03: DefineComponent<IconProps>
export declare const Monitor02: DefineComponent<IconProps>
export declare const Monitor01: DefineComponent<IconProps>
export declare const Modem02: DefineComponent<IconProps>
export declare const Modem01: DefineComponent<IconProps>
export declare const Minus: DefineComponent<IconProps>
export declare const MinusSquare: DefineComponent<IconProps>
export declare const MinusCircle: DefineComponent<IconProps>
export declare const Minimize02: DefineComponent<IconProps>
export declare const Minimize01: DefineComponent<IconProps>
export declare const Microscope: DefineComponent<IconProps>
export declare const MicrophoneOff02: DefineComponent<IconProps>
export declare const MicrophoneOff01: DefineComponent<IconProps>
export declare const Microphone02: DefineComponent<IconProps>
export declare const Microphone01: DefineComponent<IconProps>
export declare const MessageXSquare: DefineComponent<IconProps>
export declare const MessageXCircle: DefineComponent<IconProps>
export declare const MessageTextSquare02: DefineComponent<IconProps>
export declare const MessageTextSquare01: DefineComponent<IconProps>
export declare const MessageTextCircle02: DefineComponent<IconProps>
export declare const MessageTextCircle01: DefineComponent<IconProps>
export declare const MessageSquare02: DefineComponent<IconProps>
export declare const MessageSquare01: DefineComponent<IconProps>
export declare const MessageSmileSquare: DefineComponent<IconProps>
export declare const MessageSmileCircle: DefineComponent<IconProps>
export declare const MessageQuestionSquare: DefineComponent<IconProps>
export declare const MessageQuestionCircle: DefineComponent<IconProps>
export declare const MessagePlusSquare: DefineComponent<IconProps>
export declare const MessagePlusCircle: DefineComponent<IconProps>
export declare const MessageNotificationSquare: DefineComponent<IconProps>
export declare const MessageNotificationCircle: DefineComponent<IconProps>
export declare const MessageHeartSquare: DefineComponent<IconProps>
export declare const MessageHeartCircle: DefineComponent<IconProps>
export declare const MessageDotsSquare: DefineComponent<IconProps>
export declare const MessageDotsCircle: DefineComponent<IconProps>
export declare const MessageCircle02: DefineComponent<IconProps>
export declare const MessageCircle01: DefineComponent<IconProps>
export declare const MessageCheckSquare: DefineComponent<IconProps>
export declare const MessageCheckCircle: DefineComponent<IconProps>
export declare const MessageChatSquare: DefineComponent<IconProps>
export declare const MessageChatCircle: DefineComponent<IconProps>
export declare const MessageAlertSquare: DefineComponent<IconProps>
export declare const MessageAlertCircle: DefineComponent<IconProps>
export declare const Menu05: DefineComponent<IconProps>
export declare const Menu04: DefineComponent<IconProps>
export declare const Menu03: DefineComponent<IconProps>
export declare const Menu02: DefineComponent<IconProps>
export declare const Menu01: DefineComponent<IconProps>
export declare const MedicalSquare: DefineComponent<IconProps>
export declare const MedicalCross: DefineComponent<IconProps>
export declare const MedicalCircle: DefineComponent<IconProps>
export declare const Maximize02: DefineComponent<IconProps>
export declare const Maximize01: DefineComponent<IconProps>
export declare const MarkerPin06: DefineComponent<IconProps>
export declare const MarkerPin05: DefineComponent<IconProps>
export declare const MarkerPin04: DefineComponent<IconProps>
export declare const MarkerPin03: DefineComponent<IconProps>
export declare const MarkerPin02: DefineComponent<IconProps>
export declare const MarkerPin01: DefineComponent<IconProps>
export declare const Mark: DefineComponent<IconProps>
export declare const Map02: DefineComponent<IconProps>
export declare const Map01: DefineComponent<IconProps>
export declare const Mail05: DefineComponent<IconProps>
export declare const Mail04: DefineComponent<IconProps>
export declare const Mail03: DefineComponent<IconProps>
export declare const Mail02: DefineComponent<IconProps>
export declare const Mail01: DefineComponent<IconProps>
export declare const MagicWand02: DefineComponent<IconProps>
export declare const MagicWand01: DefineComponent<IconProps>
export declare const Luggage03: DefineComponent<IconProps>
export declare const Luggage02: DefineComponent<IconProps>
export declare const Luggage01: DefineComponent<IconProps>
export declare const LogOut04: DefineComponent<IconProps>
export declare const LogOut03: DefineComponent<IconProps>
export declare const LogOut02: DefineComponent<IconProps>
export declare const LogOut01: DefineComponent<IconProps>
export declare const LogIn04: DefineComponent<IconProps>
export declare const LogIn03: DefineComponent<IconProps>
export declare const LogIn02: DefineComponent<IconProps>
export declare const LogIn01: DefineComponent<IconProps>
export declare const LockUnlocked04: DefineComponent<IconProps>
export declare const LockUnlocked03: DefineComponent<IconProps>
export declare const LockUnlocked02: DefineComponent<IconProps>
export declare const LockUnlocked01: DefineComponent<IconProps>
export declare const LockKeyholeSquare: DefineComponent<IconProps>
export declare const LockKeyholeCircle: DefineComponent<IconProps>
export declare const Lock04: DefineComponent<IconProps>
export declare const Lock03: DefineComponent<IconProps>
export declare const Lock02: DefineComponent<IconProps>
export declare const Lock01: DefineComponent<IconProps>
export declare const Loading03: DefineComponent<IconProps>
export declare const Loading02: DefineComponent<IconProps>
export declare const Loading01: DefineComponent<IconProps>
export declare const List: DefineComponent<IconProps>
export declare const LinkExternal02: DefineComponent<IconProps>
export declare const LinkExternal01: DefineComponent<IconProps>
export declare const LinkBroken02: DefineComponent<IconProps>
export declare const LinkBroken01: DefineComponent<IconProps>
export declare const Link05: DefineComponent<IconProps>
export declare const Link04: DefineComponent<IconProps>
export declare const Link03: DefineComponent<IconProps>
export declare const Link02: DefineComponent<IconProps>
export declare const Link01: DefineComponent<IconProps>
export declare const LineHeight: DefineComponent<IconProps>
export declare const LineChartUp05: DefineComponent<IconProps>
export declare const LineChartUp04: DefineComponent<IconProps>
export declare const LineChartUp03: DefineComponent<IconProps>
export declare const LineChartUp02: DefineComponent<IconProps>
export declare const LineChartUp01: DefineComponent<IconProps>
export declare const LineChartDown05: DefineComponent<IconProps>
export declare const LineChartDown04: DefineComponent<IconProps>
export declare const LineChartDown03: DefineComponent<IconProps>
export declare const LineChartDown02: DefineComponent<IconProps>
export declare const LineChartDown01: DefineComponent<IconProps>
export declare const Lightning02: DefineComponent<IconProps>
export declare const Lightning01: DefineComponent<IconProps>
export declare const Lightbulb05: DefineComponent<IconProps>
export declare const Lightbulb04: DefineComponent<IconProps>
export declare const Lightbulb03: DefineComponent<IconProps>
export declare const Lightbulb02: DefineComponent<IconProps>
export declare const Lightbulb01: DefineComponent<IconProps>
export declare const LifeBuoy02: DefineComponent<IconProps>
export declare const LifeBuoy01: DefineComponent<IconProps>
export declare const LetterSpacing02: DefineComponent<IconProps>
export declare const LetterSpacing01: DefineComponent<IconProps>
export declare const LeftIndent02: DefineComponent<IconProps>
export declare const LeftIndent01: DefineComponent<IconProps>
export declare const LayoutTop: DefineComponent<IconProps>
export declare const LayoutRight: DefineComponent<IconProps>
export declare const LayoutLeft: DefineComponent<IconProps>
export declare const LayoutGrid02: DefineComponent<IconProps>
export declare const LayoutGrid01: DefineComponent<IconProps>
export declare const LayoutBottom: DefineComponent<IconProps>
export declare const LayoutAlt04: DefineComponent<IconProps>
export declare const LayoutAlt03: DefineComponent<IconProps>
export declare const LayoutAlt02: DefineComponent<IconProps>
export declare const LayoutAlt01: DefineComponent<IconProps>
export declare const LayersTwo02: DefineComponent<IconProps>
export declare const LayersTwo01: DefineComponent<IconProps>
export declare const LayersThree02: DefineComponent<IconProps>
export declare const LayersThree01: DefineComponent<IconProps>
export declare const LayerSingle: DefineComponent<IconProps>
export declare const Laptop02: DefineComponent<IconProps>
export declare const Laptop01: DefineComponent<IconProps>
export declare const Keyboard02: DefineComponent<IconProps>
export declare const Keyboard01: DefineComponent<IconProps>
export declare const Key02: DefineComponent<IconProps>
export declare const Key01: DefineComponent<IconProps>
export declare const ItalicSquare: DefineComponent<IconProps>
export declare const Italic02: DefineComponent<IconProps>
export declare const Italic01: DefineComponent<IconProps>
export declare const IntersectSquare: DefineComponent<IconProps>
export declare const IntersectCircle: DefineComponent<IconProps>
export declare const InfoSquare: DefineComponent<IconProps>
export declare const InfoOctagon: DefineComponent<IconProps>
export declare const InfoHexagon: DefineComponent<IconProps>
export declare const InfoCircle: DefineComponent<IconProps>
export declare const Infinity: DefineComponent<IconProps>
export declare const Inbox02: DefineComponent<IconProps>
export declare const Inbox01: DefineComponent<IconProps>
export declare const ImageX: DefineComponent<IconProps>
export declare const ImageUser: DefineComponent<IconProps>
export declare const ImageUserX: DefineComponent<IconProps>
export declare const ImageUserUp: DefineComponent<IconProps>
export declare const ImageUserRight: DefineComponent<IconProps>
export declare const ImageUserPlus: DefineComponent<IconProps>
export declare const ImageUserLeft: DefineComponent<IconProps>
export declare const ImageUserDown: DefineComponent<IconProps>
export declare const ImageUserCheck: DefineComponent<IconProps>
export declare const ImageUp: DefineComponent<IconProps>
export declare const ImageRight: DefineComponent<IconProps>
export declare const ImagePlus: DefineComponent<IconProps>
export declare const ImageLeft: DefineComponent<IconProps>
export declare const ImageIndentRight: DefineComponent<IconProps>
export declare const ImageIndentLeft: DefineComponent<IconProps>
export declare const ImageDown: DefineComponent<IconProps>
export declare const ImageCheck: DefineComponent<IconProps>
export declare const Image05: DefineComponent<IconProps>
export declare const Image04: DefineComponent<IconProps>
export declare const Image03: DefineComponent<IconProps>
export declare const Image02: DefineComponent<IconProps>
export declare const Image01: DefineComponent<IconProps>
export declare const Hurricane03: DefineComponent<IconProps>
export declare const Hurricane02: DefineComponent<IconProps>
export declare const Hurricane01: DefineComponent<IconProps>
export declare const Hourglass03: DefineComponent<IconProps>
export declare const Hourglass02: DefineComponent<IconProps>
export declare const Hourglass01: DefineComponent<IconProps>
export declare const HorizontalBarChart03: DefineComponent<IconProps>
export declare const HorizontalBarChart02: DefineComponent<IconProps>
export declare const HorizontalBarChart01: DefineComponent<IconProps>
export declare const HomeSmile: DefineComponent<IconProps>
export declare const HomeLine: DefineComponent<IconProps>
export declare const Home05: DefineComponent<IconProps>
export declare const Home04: DefineComponent<IconProps>
export declare const Home03: DefineComponent<IconProps>
export declare const Home02: DefineComponent<IconProps>
export declare const Home01: DefineComponent<IconProps>
export declare const Hexagon02: DefineComponent<IconProps>
export declare const Hexagon01: DefineComponent<IconProps>
export declare const HelpSquare: DefineComponent<IconProps>
export declare const HelpOctagon: DefineComponent<IconProps>
export declare const HelpOctagon1: DefineComponent<IconProps>
export declare const HelpCircle: DefineComponent<IconProps>
export declare const Hearts: DefineComponent<IconProps>
export declare const Heart: DefineComponent<IconProps>
export declare const HeartSquare: DefineComponent<IconProps>
export declare const HeartRounded: DefineComponent<IconProps>
export declare const HeartOctagon: DefineComponent<IconProps>
export declare const HeartHexagon: DefineComponent<IconProps>
export declare const HeartHand: DefineComponent<IconProps>
export declare const HeartCircle: DefineComponent<IconProps>
export declare const Headphones02: DefineComponent<IconProps>
export declare const Headphones01: DefineComponent<IconProps>
export declare const HeadingSquare: DefineComponent<IconProps>
export declare const Heading02: DefineComponent<IconProps>
export declare const Heading01: DefineComponent<IconProps>
export declare const Hash02: DefineComponent<IconProps>
export declare const Hash01: DefineComponent<IconProps>
export declare const HardDrive: DefineComponent<IconProps>
export declare const Hand: DefineComponent<IconProps>
export declare const GridDotsVerticalCenter: DefineComponent<IconProps>
export declare const GridDotsTop: DefineComponent<IconProps>
export declare const GridDotsRight: DefineComponent<IconProps>
export declare const GridDotsOuter: DefineComponent<IconProps>
export declare const GridDotsLeft: DefineComponent<IconProps>
export declare const GridDotsHorizontalCenter: DefineComponent<IconProps>
export declare const GridDotsBottom: DefineComponent<IconProps>
export declare const GridDotsBlank: DefineComponent<IconProps>
export declare const Grid03: DefineComponent<IconProps>
export declare const Grid02: DefineComponent<IconProps>
export declare const Grid01: DefineComponent<IconProps>
export declare const GraduationHat02: DefineComponent<IconProps>
export declare const GraduationHat01: DefineComponent<IconProps>
export declare const GoogleChrome: DefineComponent<IconProps>
export declare const GlobeSlated02: DefineComponent<IconProps>
export declare const GlobeSlated01: DefineComponent<IconProps>
export declare const Globe06: DefineComponent<IconProps>
export declare const Globe05: DefineComponent<IconProps>
export declare const Globe04: DefineComponent<IconProps>
export declare const Globe03: DefineComponent<IconProps>
export declare const Globe02: DefineComponent<IconProps>
export declare const Globe01: DefineComponent<IconProps>
export declare const Glasses02: DefineComponent<IconProps>
export declare const Glasses01: DefineComponent<IconProps>
export declare const GitPullRequest: DefineComponent<IconProps>
export declare const GitMerge: DefineComponent<IconProps>
export declare const GitCommit: DefineComponent<IconProps>
export declare const GitBranch02: DefineComponent<IconProps>
export declare const GitBranch01: DefineComponent<IconProps>
export declare const Gift02: DefineComponent<IconProps>
export declare const Gift01: DefineComponent<IconProps>
export declare const GamingPad02: DefineComponent<IconProps>
export declare const GamingPad01: DefineComponent<IconProps>
export declare const Framer: DefineComponent<IconProps>
export declare const Folder: DefineComponent<IconProps>
export declare const FolderX: DefineComponent<IconProps>
export declare const FolderShield: DefineComponent<IconProps>
export declare const FolderSearch: DefineComponent<IconProps>
export declare const FolderQuestion: DefineComponent<IconProps>
export declare const FolderPlus: DefineComponent<IconProps>
export declare const FolderMinus: DefineComponent<IconProps>
export declare const FolderLock: DefineComponent<IconProps>
export declare const FolderDownload: DefineComponent<IconProps>
export declare const FolderCode: DefineComponent<IconProps>
export declare const FolderClosed: DefineComponent<IconProps>
export declare const FolderCheck: DefineComponent<IconProps>
export declare const FlipForward: DefineComponent<IconProps>
export declare const FlipBackward: DefineComponent<IconProps>
export declare const FlexAlignTop: DefineComponent<IconProps>
export declare const FlexAlignRight: DefineComponent<IconProps>
export declare const FlexAlignLeft: DefineComponent<IconProps>
export declare const FlexAlignBottom: DefineComponent<IconProps>
export declare const Flash: DefineComponent<IconProps>
export declare const FlashOff: DefineComponent<IconProps>
export declare const Flag06: DefineComponent<IconProps>
export declare const Flag05: DefineComponent<IconProps>
export declare const Flag04: DefineComponent<IconProps>
export declare const Flag03: DefineComponent<IconProps>
export declare const Flag02: DefineComponent<IconProps>
export declare const Flag01: DefineComponent<IconProps>
export declare const Fingerprint04: DefineComponent<IconProps>
export declare const Fingerprint03: DefineComponent<IconProps>
export declare const Fingerprint02: DefineComponent<IconProps>
export declare const Fingerprint01: DefineComponent<IconProps>
export declare const FilterLines: DefineComponent<IconProps>
export declare const FilterFunnel02: DefineComponent<IconProps>
export declare const FilterFunnel01: DefineComponent<IconProps>
export declare const Film03: DefineComponent<IconProps>
export declare const Film02: DefineComponent<IconProps>
export declare const Film01: DefineComponent<IconProps>
export declare const FileX03: DefineComponent<IconProps>
export declare const FileX02: DefineComponent<IconProps>
export declare const FileX01: DefineComponent<IconProps>
export declare const FileShield03: DefineComponent<IconProps>
export declare const FileShield02: DefineComponent<IconProps>
export declare const FileShield01: DefineComponent<IconProps>
export declare const FileSearch03: DefineComponent<IconProps>
export declare const FileSearch02: DefineComponent<IconProps>
export declare const FileSearch01: DefineComponent<IconProps>
export declare const FileQuestion03: DefineComponent<IconProps>
export declare const FileQuestion02: DefineComponent<IconProps>
export declare const FileQuestion01: DefineComponent<IconProps>
export declare const FilePlus03: DefineComponent<IconProps>
export declare const FilePlus02: DefineComponent<IconProps>
export declare const FilePlus01: DefineComponent<IconProps>
export declare const FileMinus03: DefineComponent<IconProps>
export declare const FileMinus02: DefineComponent<IconProps>
export declare const FileMinus01: DefineComponent<IconProps>
export declare const FileLock03: DefineComponent<IconProps>
export declare const FileLock02: DefineComponent<IconProps>
export declare const FileLock01: DefineComponent<IconProps>
export declare const FileHeart03: DefineComponent<IconProps>
export declare const FileHeart02: DefineComponent<IconProps>
export declare const FileHeart01: DefineComponent<IconProps>
export declare const FileDownload03: DefineComponent<IconProps>
export declare const FileDownload02: DefineComponent<IconProps>
export declare const FileDownload01: DefineComponent<IconProps>
export declare const FileCode02: DefineComponent<IconProps>
export declare const FileCode01: DefineComponent<IconProps>
export declare const FileCheck03: DefineComponent<IconProps>
export declare const FileCheck02: DefineComponent<IconProps>
export declare const FileCheck01: DefineComponent<IconProps>
export declare const FileAttachment05: DefineComponent<IconProps>
export declare const FileAttachment04: DefineComponent<IconProps>
export declare const FileAttachment03: DefineComponent<IconProps>
export declare const FileAttachment02: DefineComponent<IconProps>
export declare const FileAttachment01: DefineComponent<IconProps>
export declare const File07: DefineComponent<IconProps>
export declare const File06: DefineComponent<IconProps>
export declare const File05: DefineComponent<IconProps>
export declare const File04: DefineComponent<IconProps>
export declare const File03: DefineComponent<IconProps>
export declare const File02: DefineComponent<IconProps>
export declare const File01: DefineComponent<IconProps>
export declare const Figma: DefineComponent<IconProps>
export declare const Feather: DefineComponent<IconProps>
export declare const FastForward: DefineComponent<IconProps>
export declare const FastBackward: DefineComponent<IconProps>
export declare const FaceWink: DefineComponent<IconProps>
export declare const FaceSmile: DefineComponent<IconProps>
export declare const FaceSad: DefineComponent<IconProps>
export declare const FaceNeutral: DefineComponent<IconProps>
export declare const FaceId: DefineComponent<IconProps>
export declare const FaceIdSquare: DefineComponent<IconProps>
export declare const FaceHappy: DefineComponent<IconProps>
export declare const FaceFrown: DefineComponent<IconProps>
export declare const FaceContent: DefineComponent<IconProps>
export declare const Eye: DefineComponent<IconProps>
export declare const EyeOff: DefineComponent<IconProps>
export declare const Expand06: DefineComponent<IconProps>
export declare const Expand05: DefineComponent<IconProps>
export declare const Expand04: DefineComponent<IconProps>
export declare const Expand03: DefineComponent<IconProps>
export declare const Expand02: DefineComponent<IconProps>
export declare const Expand01: DefineComponent<IconProps>
export declare const Eraser: DefineComponent<IconProps>
export declare const Equal: DefineComponent<IconProps>
export declare const EqualNot: DefineComponent<IconProps>
export declare const Edit05: DefineComponent<IconProps>
export declare const Edit04: DefineComponent<IconProps>
export declare const Edit03: DefineComponent<IconProps>
export declare const Edit02: DefineComponent<IconProps>
export declare const Edit01: DefineComponent<IconProps>
export declare const Dropper: DefineComponent<IconProps>
export declare const Droplets03: DefineComponent<IconProps>
export declare const Droplets02: DefineComponent<IconProps>
export declare const Droplets01: DefineComponent<IconProps>
export declare const Drop: DefineComponent<IconProps>
export declare const DownloadCloud02: DefineComponent<IconProps>
export declare const DownloadCloud01: DefineComponent<IconProps>
export declare const Download04: DefineComponent<IconProps>
export declare const Download03: DefineComponent<IconProps>
export declare const Download02: DefineComponent<IconProps>
export declare const Download01: DefineComponent<IconProps>
export declare const DotsVertical: DefineComponent<IconProps>
export declare const DotsHorizontal: DefineComponent<IconProps>
export declare const DotsGrid: DefineComponent<IconProps>
export declare const Dotpoints02: DefineComponent<IconProps>
export declare const Dotpoints01: DefineComponent<IconProps>
export declare const Divider: DefineComponent<IconProps>
export declare const Divide03: DefineComponent<IconProps>
export declare const Divide02: DefineComponent<IconProps>
export declare const Divide01: DefineComponent<IconProps>
export declare const DistributeSpacingVertical: DefineComponent<IconProps>
export declare const DistributeSpacingHorizontal: DefineComponent<IconProps>
export declare const Disc02: DefineComponent<IconProps>
export declare const Disc01: DefineComponent<IconProps>
export declare const Dice6: DefineComponent<IconProps>
export declare const Dice5: DefineComponent<IconProps>
export declare const Dice4: DefineComponent<IconProps>
export declare const Dice3: DefineComponent<IconProps>
export declare const Dice2: DefineComponent<IconProps>
export declare const Dice1: DefineComponent<IconProps>
export declare const Diamond02: DefineComponent<IconProps>
export declare const Diamond01: DefineComponent<IconProps>
export declare const Delete: DefineComponent<IconProps>
export declare const Dataflow04: DefineComponent<IconProps>
export declare const Dataflow03: DefineComponent<IconProps>
export declare const Dataflow02: DefineComponent<IconProps>
export declare const Dataflow01: DefineComponent<IconProps>
export declare const Database03: DefineComponent<IconProps>
export declare const Database02: DefineComponent<IconProps>
export declare const Database01: DefineComponent<IconProps>
export declare const Data: DefineComponent<IconProps>
export declare const CursorClick02: DefineComponent<IconProps>
export declare const CursorClick01: DefineComponent<IconProps>
export declare const CursorBox: DefineComponent<IconProps>
export declare const Cursor04: DefineComponent<IconProps>
export declare const Cursor03: DefineComponent<IconProps>
export declare const Cursor02: DefineComponent<IconProps>
export declare const Cursor01: DefineComponent<IconProps>
export declare const CurrencyYen: DefineComponent<IconProps>
export declare const CurrencyYenCircle: DefineComponent<IconProps>
export declare const CurrencyRupee: DefineComponent<IconProps>
export declare const CurrencyRupeeCircle: DefineComponent<IconProps>
export declare const CurrencyRuble: DefineComponent<IconProps>
export declare const CurrencyRubleCircle: DefineComponent<IconProps>
export declare const CurrencyPound: DefineComponent<IconProps>
export declare const CurrencyPoundCircle: DefineComponent<IconProps>
export declare const CurrencyEuro: DefineComponent<IconProps>
export declare const CurrencyEuroCircle: DefineComponent<IconProps>
export declare const CurrencyEthereum: DefineComponent<IconProps>
export declare const CurrencyEthereumCircle: DefineComponent<IconProps>
export declare const CurrencyDollar: DefineComponent<IconProps>
export declare const CurrencyDollarCircle: DefineComponent<IconProps>
export declare const CurrencyBitcoin: DefineComponent<IconProps>
export declare const CurrencyBitcoinCircle: DefineComponent<IconProps>
export declare const CubeOutline: DefineComponent<IconProps>
export declare const Cube04: DefineComponent<IconProps>
export declare const Cube03: DefineComponent<IconProps>
export declare const Cube02: DefineComponent<IconProps>
export declare const Cube01: DefineComponent<IconProps>
export declare const Cryptocurrency04: DefineComponent<IconProps>
export declare const Cryptocurrency03: DefineComponent<IconProps>
export declare const Cryptocurrency02: DefineComponent<IconProps>
export declare const Cryptocurrency01: DefineComponent<IconProps>
export declare const Crop02: DefineComponent<IconProps>
export declare const Crop01: DefineComponent<IconProps>
export declare const CreditCardX: DefineComponent<IconProps>
export declare const CreditCardUpload: DefineComponent<IconProps>
export declare const CreditCardUp: DefineComponent<IconProps>
export declare const CreditCardShield: DefineComponent<IconProps>
export declare const CreditCardSearch: DefineComponent<IconProps>
export declare const CreditCardRefresh: DefineComponent<IconProps>
export declare const CreditCardPlus: DefineComponent<IconProps>
export declare const CreditCardMinus: DefineComponent<IconProps>
export declare const CreditCardLock: DefineComponent<IconProps>
export declare const CreditCardEdit: DefineComponent<IconProps>
export declare const CreditCardDownload: DefineComponent<IconProps>
export declare const CreditCardDown: DefineComponent<IconProps>
export declare const CreditCardCheck: DefineComponent<IconProps>
export declare const CreditCard02: DefineComponent<IconProps>
export declare const CreditCard01: DefineComponent<IconProps>
export declare const CpuChip02: DefineComponent<IconProps>
export declare const CpuChip01: DefineComponent<IconProps>
export declare const CornerUpRight: DefineComponent<IconProps>
export declare const CornerUpLeft: DefineComponent<IconProps>
export declare const CornerRightUp: DefineComponent<IconProps>
export declare const CornerRightDown: DefineComponent<IconProps>
export declare const CornerLeftUp: DefineComponent<IconProps>
export declare const CornerLeftDown: DefineComponent<IconProps>
export declare const CornerDownRight: DefineComponent<IconProps>
export declare const CornerDownLeft: DefineComponent<IconProps>
export declare const Copy07: DefineComponent<IconProps>
export declare const Copy06: DefineComponent<IconProps>
export declare const Copy05: DefineComponent<IconProps>
export declare const Copy04: DefineComponent<IconProps>
export declare const Copy03: DefineComponent<IconProps>
export declare const Copy02: DefineComponent<IconProps>
export declare const Copy01: DefineComponent<IconProps>
export declare const Contrast03: DefineComponent<IconProps>
export declare const Contrast02: DefineComponent<IconProps>
export declare const Contrast01: DefineComponent<IconProps>
export declare const Container: DefineComponent<IconProps>
export declare const Compass: DefineComponent<IconProps>
export declare const Compass03: DefineComponent<IconProps>
export declare const Compass02: DefineComponent<IconProps>
export declare const Compass01: DefineComponent<IconProps>
export declare const Command: DefineComponent<IconProps>
export declare const Columns03: DefineComponent<IconProps>
export declare const Columns02: DefineComponent<IconProps>
export declare const Columns01: DefineComponent<IconProps>
export declare const Colors: DefineComponent<IconProps>
export declare const Colors1: DefineComponent<IconProps>
export declare const CoinsSwap02: DefineComponent<IconProps>
export declare const CoinsSwap01: DefineComponent<IconProps>
export declare const CoinsStacked04: DefineComponent<IconProps>
export declare const CoinsStacked03: DefineComponent<IconProps>
export declare const CoinsStacked02: DefineComponent<IconProps>
export declare const CoinsStacked01: DefineComponent<IconProps>
export declare const CoinsHand: DefineComponent<IconProps>
export declare const Coins04: DefineComponent<IconProps>
export declare const Coins03: DefineComponent<IconProps>
export declare const Coins02: DefineComponent<IconProps>
export declare const Coins01: DefineComponent<IconProps>
export declare const Codepen: DefineComponent<IconProps>
export declare const CodeSquare02: DefineComponent<IconProps>
export declare const CodeSquare01: DefineComponent<IconProps>
export declare const CodeSnippet02: DefineComponent<IconProps>
export declare const CodeSnippet01: DefineComponent<IconProps>
export declare const CodeCircle03: DefineComponent<IconProps>
export declare const CodeCircle02: DefineComponent<IconProps>
export declare const CodeCircle01: DefineComponent<IconProps>
export declare const CodeBrowser: DefineComponent<IconProps>
export declare const Code02: DefineComponent<IconProps>
export declare const Code01: DefineComponent<IconProps>
export declare const CloudSun03: DefineComponent<IconProps>
export declare const CloudSun02: DefineComponent<IconProps>
export declare const CloudSun01: DefineComponent<IconProps>
export declare const CloudSnowing02: DefineComponent<IconProps>
export declare const CloudSnowing01: DefineComponent<IconProps>
export declare const CloudRaining06: DefineComponent<IconProps>
export declare const CloudRaining05: DefineComponent<IconProps>
export declare const CloudRaining04: DefineComponent<IconProps>
export declare const CloudRaining03: DefineComponent<IconProps>
export declare const CloudRaining02: DefineComponent<IconProps>
export declare const CloudRaining01: DefineComponent<IconProps>
export declare const CloudOff: DefineComponent<IconProps>
export declare const CloudMoon: DefineComponent<IconProps>
export declare const CloudLightning: DefineComponent<IconProps>
export declare const CloudBlank02: DefineComponent<IconProps>
export declare const CloudBlank01: DefineComponent<IconProps>
export declare const Cloud03: DefineComponent<IconProps>
export declare const Cloud02: DefineComponent<IconProps>
export declare const Cloud01: DefineComponent<IconProps>
export declare const Clock: DefineComponent<IconProps>
export declare const ClockStopwatch: DefineComponent<IconProps>
export declare const ClockSnooze: DefineComponent<IconProps>
export declare const ClockRewind: DefineComponent<IconProps>
export declare const ClockRefresh: DefineComponent<IconProps>
export declare const ClockPlus: DefineComponent<IconProps>
export declare const ClockFastForward: DefineComponent<IconProps>
export declare const ClockCheck: DefineComponent<IconProps>
export declare const Clipboard: DefineComponent<IconProps>
export declare const ClipboardX: DefineComponent<IconProps>
export declare const ClipboardPlus: DefineComponent<IconProps>
export declare const ClipboardMinus: DefineComponent<IconProps>
export declare const ClipboardDownload: DefineComponent<IconProps>
export declare const ClipboardCheck: DefineComponent<IconProps>
export declare const ClipboardAttachment: DefineComponent<IconProps>
export declare const Clapperboard: DefineComponent<IconProps>
export declare const Circle: DefineComponent<IconProps>
export declare const CircleCut: DefineComponent<IconProps>
export declare const ChromeCast: DefineComponent<IconProps>
export declare const ChevronUp: DefineComponent<IconProps>
export declare const ChevronUpDouble: DefineComponent<IconProps>
export declare const ChevronSelectorVertical: DefineComponent<IconProps>
export declare const ChevronSelectorHorizontal: DefineComponent<IconProps>
export declare const ChevronRight: DefineComponent<IconProps>
export declare const ChevronRightDouble: DefineComponent<IconProps>
export declare const ChevronLeft: DefineComponent<IconProps>
export declare const ChevronLeftDouble: DefineComponent<IconProps>
export declare const ChevronDown: DefineComponent<IconProps>
export declare const ChevronDownDouble: DefineComponent<IconProps>
export declare const Check: DefineComponent<IconProps>
export declare const CheckVerified03: DefineComponent<IconProps>
export declare const CheckVerified02: DefineComponent<IconProps>
export declare const CheckVerified01: DefineComponent<IconProps>
export declare const CheckSquare: DefineComponent<IconProps>
export declare const CheckSquareBroken: DefineComponent<IconProps>
export declare const CheckHeart: DefineComponent<IconProps>
export declare const CheckDone02: DefineComponent<IconProps>
export declare const CheckDone01: DefineComponent<IconProps>
export declare const CheckCircle: DefineComponent<IconProps>
export declare const CheckCircleBroken: DefineComponent<IconProps>
export declare const ChartBreakoutSquare: DefineComponent<IconProps>
export declare const ChartBreakoutCircle: DefineComponent<IconProps>
export declare const Certificate02: DefineComponent<IconProps>
export declare const Certificate01: DefineComponent<IconProps>
export declare const Car02: DefineComponent<IconProps>
export declare const Car01: DefineComponent<IconProps>
export declare const CameraPlus: DefineComponent<IconProps>
export declare const CameraOff: DefineComponent<IconProps>
export declare const CameraLens: DefineComponent<IconProps>
export declare const Camera03: DefineComponent<IconProps>
export declare const Camera02: DefineComponent<IconProps>
export declare const Camera01: DefineComponent<IconProps>
export declare const Calendar: DefineComponent<IconProps>
export declare const CalendarPlus02: DefineComponent<IconProps>
export declare const CalendarPlus01: DefineComponent<IconProps>
export declare const CalendarMinus02: DefineComponent<IconProps>
export declare const CalendarMinus01: DefineComponent<IconProps>
export declare const CalendarHeart02: DefineComponent<IconProps>
export declare const CalendarHeart01: DefineComponent<IconProps>
export declare const CalendarDate: DefineComponent<IconProps>
export declare const CalendarCheck02: DefineComponent<IconProps>
export declare const CalendarCheck01: DefineComponent<IconProps>
export declare const Calculator: DefineComponent<IconProps>
export declare const Bus: DefineComponent<IconProps>
export declare const Building08: DefineComponent<IconProps>
export declare const Building07: DefineComponent<IconProps>
export declare const Building06: DefineComponent<IconProps>
export declare const Building05: DefineComponent<IconProps>
export declare const Building04: DefineComponent<IconProps>
export declare const Building03: DefineComponent<IconProps>
export declare const Building02: DefineComponent<IconProps>
export declare const Building01: DefineComponent<IconProps>
export declare const Brush03: DefineComponent<IconProps>
export declare const Brush02: DefineComponent<IconProps>
export declare const Brush01: DefineComponent<IconProps>
export declare const Browser: DefineComponent<IconProps>
export declare const Briefcase02: DefineComponent<IconProps>
export declare const Briefcase01: DefineComponent<IconProps>
export declare const Brackets: DefineComponent<IconProps>
export declare const BracketsX: DefineComponent<IconProps>
export declare const BracketsSlash: DefineComponent<IconProps>
export declare const BracketsPlus: DefineComponent<IconProps>
export declare const BracketsMinus: DefineComponent<IconProps>
export declare const BracketsEllipses: DefineComponent<IconProps>
export declare const BracketsCheck: DefineComponent<IconProps>
export declare const Box: DefineComponent<IconProps>
export declare const Bookmark: DefineComponent<IconProps>
export declare const BookmarkX: DefineComponent<IconProps>
export declare const BookmarkMinus: DefineComponent<IconProps>
export declare const BookmarkCheck: DefineComponent<IconProps>
export declare const BookmarkAdd: DefineComponent<IconProps>
export declare const BookOpen02: DefineComponent<IconProps>
export declare const BookOpen01: DefineComponent<IconProps>
export declare const BookClosed: DefineComponent<IconProps>
export declare const BoldSquare: DefineComponent<IconProps>
export declare const Bold02: DefineComponent<IconProps>
export declare const Bold01: DefineComponent<IconProps>
export declare const BluetoothSignal: DefineComponent<IconProps>
export declare const BluetoothOn: DefineComponent<IconProps>
export declare const BluetoothOff: DefineComponent<IconProps>
export declare const BluetoothConnect: DefineComponent<IconProps>
export declare const BezierCurve03: DefineComponent<IconProps>
export declare const BezierCurve02: DefineComponent<IconProps>
export declare const BezierCurve01: DefineComponent<IconProps>
export declare const BellRinging04: DefineComponent<IconProps>
export declare const BellRinging03: DefineComponent<IconProps>
export declare const BellRinging02: DefineComponent<IconProps>
export declare const BellRinging01: DefineComponent<IconProps>
export declare const BellPlus: DefineComponent<IconProps>
export declare const BellOff03: DefineComponent<IconProps>
export declare const BellOff02: DefineComponent<IconProps>
export declare const BellOff01: DefineComponent<IconProps>
export declare const BellMinus: DefineComponent<IconProps>
export declare const Bell04: DefineComponent<IconProps>
export declare const Bell03: DefineComponent<IconProps>
export declare const Bell02: DefineComponent<IconProps>
export declare const Bell01: DefineComponent<IconProps>
export declare const Beaker02: DefineComponent<IconProps>
export declare const Beaker01: DefineComponent<IconProps>
export declare const BatteryMid: DefineComponent<IconProps>
export declare const BatteryLow: DefineComponent<IconProps>
export declare const BatteryFull: DefineComponent<IconProps>
export declare const BatteryEmpty: DefineComponent<IconProps>
export declare const BatteryCharging02: DefineComponent<IconProps>
export declare const BatteryCharging01: DefineComponent<IconProps>
export declare const BarLineChart: DefineComponent<IconProps>
export declare const BarChartSquareUp: DefineComponent<IconProps>
export declare const BarChartSquarePlus: DefineComponent<IconProps>
export declare const BarChartSquareMinus: DefineComponent<IconProps>
export declare const BarChartSquareDown: DefineComponent<IconProps>
export declare const BarChartSquare03: DefineComponent<IconProps>
export declare const BarChartSquare02: DefineComponent<IconProps>
export declare const BarChartSquare01: DefineComponent<IconProps>
export declare const BarChartCircle03: DefineComponent<IconProps>
export declare const BarChartCircle02: DefineComponent<IconProps>
export declare const BarChartCircle01: DefineComponent<IconProps>
export declare const BarChart12: DefineComponent<IconProps>
export declare const BarChart11: DefineComponent<IconProps>
export declare const BarChart10: DefineComponent<IconProps>
export declare const BarChart09: DefineComponent<IconProps>
export declare const BarChart08: DefineComponent<IconProps>
export declare const BarChart07: DefineComponent<IconProps>
export declare const BarChart06: DefineComponent<IconProps>
export declare const BarChart05: DefineComponent<IconProps>
export declare const BarChart04: DefineComponent<IconProps>
export declare const BarChart03: DefineComponent<IconProps>
export declare const BarChart02: DefineComponent<IconProps>
export declare const BarChart01: DefineComponent<IconProps>
export declare const Bank: DefineComponent<IconProps>
export declare const BankNote03: DefineComponent<IconProps>
export declare const BankNote02: DefineComponent<IconProps>
export declare const BankNote01: DefineComponent<IconProps>
export declare const Backpack: DefineComponent<IconProps>
export declare const Award05: DefineComponent<IconProps>
export declare const Award04: DefineComponent<IconProps>
export declare const Award03: DefineComponent<IconProps>
export declare const Award02: DefineComponent<IconProps>
export declare const Award01: DefineComponent<IconProps>
export declare const Attachment02: DefineComponent<IconProps>
export declare const Attachment01: DefineComponent<IconProps>
export declare const Atom02: DefineComponent<IconProps>
export declare const Atom01: DefineComponent<IconProps>
export declare const AtSign: DefineComponent<IconProps>
export declare const Asterisk02: DefineComponent<IconProps>
export declare const Asterisk01: DefineComponent<IconProps>
export declare const ArrowsUp: DefineComponent<IconProps>
export declare const ArrowsTriangle: DefineComponent<IconProps>
export declare const ArrowsRight: DefineComponent<IconProps>
export declare const ArrowsLeft: DefineComponent<IconProps>
export declare const ArrowsDown: DefineComponent<IconProps>
export declare const ArrowUp: DefineComponent<IconProps>
export declare const ArrowUpRight: DefineComponent<IconProps>
export declare const ArrowUpLeft: DefineComponent<IconProps>
export declare const ArrowSquareUp: DefineComponent<IconProps>
export declare const ArrowSquareUpRight: DefineComponent<IconProps>
export declare const ArrowSquareUpLeft: DefineComponent<IconProps>
export declare const ArrowSquareRight: DefineComponent<IconProps>
export declare const ArrowSquareLeft: DefineComponent<IconProps>
export declare const ArrowSquareDown: DefineComponent<IconProps>
export declare const ArrowSquareDownRight: DefineComponent<IconProps>
export declare const ArrowSquareDownLeft: DefineComponent<IconProps>
export declare const ArrowRight: DefineComponent<IconProps>
export declare const ArrowNarrowUp: DefineComponent<IconProps>
export declare const ArrowNarrowUpRight: DefineComponent<IconProps>
export declare const ArrowNarrowUpLeft: DefineComponent<IconProps>
export declare const ArrowNarrowRight: DefineComponent<IconProps>
export declare const ArrowNarrowLeft: DefineComponent<IconProps>
export declare const ArrowNarrowDown: DefineComponent<IconProps>
export declare const ArrowNarrowDownRight: DefineComponent<IconProps>
export declare const ArrowNarrowDownLeft: DefineComponent<IconProps>
export declare const ArrowLeft: DefineComponent<IconProps>
export declare const ArrowDown: DefineComponent<IconProps>
export declare const ArrowDownRight: DefineComponent<IconProps>
export declare const ArrowDownLeft: DefineComponent<IconProps>
export declare const ArrowCircleUp: DefineComponent<IconProps>
export declare const ArrowCircleUpRight: DefineComponent<IconProps>
export declare const ArrowCircleUpLeft: DefineComponent<IconProps>
export declare const ArrowCircleRight: DefineComponent<IconProps>
export declare const ArrowCircleLeft: DefineComponent<IconProps>
export declare const ArrowCircleDown: DefineComponent<IconProps>
export declare const ArrowCircleDownRight: DefineComponent<IconProps>
export declare const ArrowCircleDownLeft: DefineComponent<IconProps>
export declare const ArrowCircleBrokenUp: DefineComponent<IconProps>
export declare const ArrowCircleBrokenUpRight: DefineComponent<IconProps>
export declare const ArrowCircleBrokenUpLeft: DefineComponent<IconProps>
export declare const ArrowCircleBrokenRight: DefineComponent<IconProps>
export declare const ArrowCircleBrokenLeft: DefineComponent<IconProps>
export declare const ArrowCircleBrokenDown: DefineComponent<IconProps>
export declare const ArrowCircleBrokenDownRight: DefineComponent<IconProps>
export declare const ArrowCircleBrokenDownLeft: DefineComponent<IconProps>
export declare const ArrowBlockUp: DefineComponent<IconProps>
export declare const ArrowBlockRight: DefineComponent<IconProps>
export declare const ArrowBlockLeft: DefineComponent<IconProps>
export declare const ArrowBlockDown: DefineComponent<IconProps>
export declare const Archive: DefineComponent<IconProps>
export declare const Announcement03: DefineComponent<IconProps>
export declare const Announcement02: DefineComponent<IconProps>
export declare const Announcement01: DefineComponent<IconProps>
export declare const Annotation: DefineComponent<IconProps>
export declare const AnnotationX: DefineComponent<IconProps>
export declare const AnnotationQuestion: DefineComponent<IconProps>
export declare const AnnotationPlus: DefineComponent<IconProps>
export declare const AnnotationInfo: DefineComponent<IconProps>
export declare const AnnotationHeart: DefineComponent<IconProps>
export declare const AnnotationDots: DefineComponent<IconProps>
export declare const AnnotationCheck: DefineComponent<IconProps>
export declare const AnnotationAlert: DefineComponent<IconProps>
export declare const Anchor: DefineComponent<IconProps>
export declare const AlignVerticalCenter02: DefineComponent<IconProps>
export declare const AlignVerticalCenter01: DefineComponent<IconProps>
export declare const AlignTopArrow02: DefineComponent<IconProps>
export declare const AlignTopArrow01: DefineComponent<IconProps>
export declare const AlignRight: DefineComponent<IconProps>
export declare const AlignRight02: DefineComponent<IconProps>
export declare const AlignRight01: DefineComponent<IconProps>
export declare const AlignLeft: DefineComponent<IconProps>
export declare const AlignLeft02: DefineComponent<IconProps>
export declare const AlignLeft01: DefineComponent<IconProps>
export declare const AlignJustify: DefineComponent<IconProps>
export declare const AlignHorizontalCentre02: DefineComponent<IconProps>
export declare const AlignHorizontalCentre01: DefineComponent<IconProps>
export declare const AlignCenter: DefineComponent<IconProps>
export declare const AlignBottom02: DefineComponent<IconProps>
export declare const AlignBottom01: DefineComponent<IconProps>
export declare const AlertTriangle: DefineComponent<IconProps>
export declare const AlertSquare: DefineComponent<IconProps>
export declare const AlertOctagon: DefineComponent<IconProps>
export declare const AlertHexagon: DefineComponent<IconProps>
export declare const AlertCircle: DefineComponent<IconProps>
export declare const AlarmClock: DefineComponent<IconProps>
export declare const AlarmClockPlus: DefineComponent<IconProps>
export declare const AlarmClockOff: DefineComponent<IconProps>
export declare const AlarmClockMinus: DefineComponent<IconProps>
export declare const AlarmClockCheck: DefineComponent<IconProps>
export declare const Airpods: DefineComponent<IconProps>
export declare const Airplay: DefineComponent<IconProps>
export declare const Activity: DefineComponent<IconProps>
export declare const ActivityHeart: DefineComponent<IconProps>
